// pimage.js
export const PROFILE_ICONS = {
    1: "images/images/coolcats/0.png",
    2: "images/images/coolcats/1.png",
    3: "images/images/coolcats/2.png",
    4: "images/images/coolcats/3.png",
    5: "images/images/coolcats/4.png",
    6: "images/images/coolcats/5.png",
    7: "images/images/coolcats/6.png",
    8: "images/images/coolcats/7.png",
    9: "images/images/coolcats/8.png",
    10: "images/images/coolcats/9.png",
    11: "images/images/coolcats/10.png",
    12: "images/images/coolcats/11.png",
    13: "images/images/coolcats/12.png",
    14: "images/images/coolcats/13.png",
    15: "images/images/coolcats/14.png",
    16: "images/images/coolcats/15.png",
    17: "images/images/coolcats/16.png",
    18: "images/images/coolcats/17.png",
    19: "images/images/coolcats/18.png",
    20: "images/images/coolcats/19.png",
    21: "images/images/coolcats/20.png",
    22: "images/images/coolcats/21.png",
    23: "images/images/coolcats/22.png",
    24: "images/images/coolcats/23.png",
    25: "images/images/coolcats/24.png",
    26: "images/images/coolcats/25.png",
    27: "images/images/coolcats/26.png",
    28: "images/images/coolcats/27.png",
    29: "images/images/coolcats/28.png",
    30: "images/images/coolcats/29.png",
    31: "images/images/coolcats/30.png",
    32: "images/images/coolcats/31.png",
    33: "images/images/coolcats/32.png",
    34: "images/images/coolcats/33.png",
    35: "images/images/coolcats/34.png",
    36: "images/images/coolcats/35.png",
    37: "images/images/coolcats/36.png",
    38: "images/images/coolcats/37.png",
    39: "images/images/coolcats/38.png",
    40: "images/images/coolcats/39.png",
    41: "images/images/coolcats/40.png",
    42: "images/images/coolcats/41.png",
    43: "images/images/coolcats/42.png",
    44: "images/images/coolcats/43.png",
    45: "images/images/coolcats/44.png",
    46: "images/images/coolcats/45.png",
    47: "images/images/coolcats/46.png",
    48: "images/images/coolcats/47.png",
    49: "images/images/coolcats/48.png",
    50: "images/images/coolcats/49.png",
    51: "images/images/coolcats/50.png",
    52: "images/images/coolcats/51.png",
    53: "images/images/coolcats/52.png",
    54: "images/images/coolcats/53.png",
    55: "images/images/coolcats/54.png",
    56: "images/images/coolcats/55.png",
    57: "images/images/coolcats/56.png",
    58: "images/images/coolcats/57.png",
    59: "images/images/coolcats/58.png",
    60: "images/images/coolcats/59.png",
    61: "images/mms.jfif"



    // 2: "images/userred.png",
    // 3: "images/usergreen.png",
    // 4: "images/useryellow.png",
    // 5: "images/thunder.gif",
    // 6: "images/male.png",
    // 7: "images/maleuser.gif",
    // 8: "images/female.png",
    // 9: "images/femaleuser.gif",
    // 10: "images/h1.jpg",
    // 11: "images/h2.jpg",
    // 12: "images/h3.jpg",
    // 13: "images/h4.jpg",
    // 14: "images/h5.jpg",
    // 15: "images/h6.jpg",
    // 16: "images/h7.jpg",
    // 17: "images/j1.jpg",
    // 18: "images/j2.jpg"
};